# Generated by Django 5.0.1 on 2024-01-15 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
